export const ROUTES = {
  HOME: "/",
  ABOUT_US: "/about-us",
  CONTACT_US: "/contact-us",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  FORGOT_PASSWORD: "/auth/request-reset-password",
  RESET_PASSWORD_CONFIRM: "/auth/reset-password/:token",
  SHOP: "/shop",
  PRODUCT_DETAILS: "/products/:slug",
  CART: "/cart",
  COMPARE: "/compare",
  USER_PROFILE: "/profile",
  WISHLIST: "/wishlist",
  PLACE_ORDER: "/order/place",
  ORDER_SHIPPING: "/order/shipping",
  ORDER_PAYMENT: "/order/payment",
  ORDER_DETAILS: "/orders/:order_number",
  ORDER_PAYMENT_SUCCESS: "/order/payment/success",
  ORDER_PAYMENT_ERROR: "/order/payment/error",
  NOT_FOUND: "*",
};
